#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m`"
fi

case "$ARCH" in
x86 | i?86) ARCH="i686";;
x86_64 | amd64) ARCH="amd64";;
arm64 | aarch64) ARCH="aarch64";;
arm*) ARCH="aarch64";;
*) error 2 "Invalid architecture '$ARCH'.";;
esac

if [ -z "$MIRROR" ]; then
    if [ "$ARCH" = 'amd64' -o "$ARCH" = 'i386' ]; then
        MIRROR="${CROUTON_MIRROR_arch:-http://mirror.csclub.uwaterloo.ca/archlinux/\$repo/os/\$arch}"
    else
        MIRROR="${CROUTON_MIRROR_alarm:-http://mirror.csclub.uwaterloo.ca/archlinuxarm/aarch64/\$repo}"
    fi
fi

